name: post_flow
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dartz: ^0.10.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  connectivity_plus: ^6.1.3
  dio: ^5.8.0+1
  mocktail: ^0.3.0 
  bloc_test: ^9.1.0
  integration_test:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


