// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAStX_wXm-RkfvYshOYetH1jT_KfEnA7HE',
    appId: '1:972921846441:web:0e232de48c7556f0fcc7b8',
    messagingSenderId: '972921846441',
    projectId: 'post-flow-a0adf',
    authDomain: 'post-flow-a0adf.firebaseapp.com',
    storageBucket: 'post-flow-a0adf.firebasestorage.app',
    measurementId: 'G-085Z6SD7QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkSTGTO9VZURNlAYCiddOkmB8f8XYf9Wk',
    appId: '1:972921846441:android:3be20e2090194d1efcc7b8',
    messagingSenderId: '972921846441',
    projectId: 'post-flow-a0adf',
    storageBucket: 'post-flow-a0adf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzkztQcptipRGzSuNJ6wh2KwJn-Fw8EzA',
    appId: '1:972921846441:ios:20428b8263f74cfcfcc7b8',
    messagingSenderId: '972921846441',
    projectId: 'post-flow-a0adf',
    storageBucket: 'post-flow-a0adf.firebasestorage.app',
    iosBundleId: 'com.example.postFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzkztQcptipRGzSuNJ6wh2KwJn-Fw8EzA',
    appId: '1:972921846441:ios:20428b8263f74cfcfcc7b8',
    messagingSenderId: '972921846441',
    projectId: 'post-flow-a0adf',
    storageBucket: 'post-flow-a0adf.firebasestorage.app',
    iosBundleId: 'com.example.postFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAStX_wXm-RkfvYshOYetH1jT_KfEnA7HE',
    appId: '1:972921846441:web:60f594cd0cc0d464fcc7b8',
    messagingSenderId: '972921846441',
    projectId: 'post-flow-a0adf',
    authDomain: 'post-flow-a0adf.firebaseapp.com',
    storageBucket: 'post-flow-a0adf.firebasestorage.app',
    measurementId: 'G-XK896DG0MD',
  );
}
